spring:
  datasource:
    # Syntax: ${VARIABLE_NAME:DEFAULT_VALUE}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/hotel_booking_db?createDatabaseIfNotExist=true}
    username: ${MYSQLUSER:root}
    password: ${MYSQLPASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Using the generic dialect to avoid the previous "MySQL8Dialect" crash
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:8080}